### ISSUE TITLE
Kill warp does not work at all when using "Warp here" or "Warp to next maneuver" 

### ISSUE THREAD

**Issue by arechsteiner** [TriggerAu/KerbalAlarmClock#145] opened 2015-06-22 17:17 UTC
Whenever I use the standard "Warp here" or "Warp to next maneuver" buttons, alarms will only spawn a message, but warps are continued. In this case, I'm warping to a maneuver while in orbit around the sun. The warp speed used by the game is max. I can see that when an alarm is reached and the message spawns, then warp is reduced by 3 units for a split second, before it returns to max speed. My guess would be that KerbalAlarmClock is trying to cancel the warp, but Kerbal is resuming it immediately.

In my current example, the failing alarms are of type "Raw Time Alarm" and "SOI change", with action "Kill Warp and Message".

**Comment by TriggerAu** [comment] 2015-06-25 03:45
Duplicate of #132 . Have spoken with ted about it and raised a feature request to allow modders to disengage the stock warp here controller.

Will push pretty hard for this in 1.1

**Comment by TriggerAu** [comment] 2015-06-25 03:45
Thanks for the bug report btw, I really appreciate people helping out :)

**Closed by TriggerAu** 2015-06-25 03:45 UTC
Labels: duplicate, KSP Bug
